name: base_project
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  visibility_detector: ^0.3.3
  connectivity_plus: ^2.3.6+1
  sqflite: any
  path: any

  dio: ^4.0.6
  retrofit: ^3.0.1+1
  hive: ^2.2.3
  json_annotation: ^4.6.0
  json_serializable: ^6.3.2

  flutter_gen: ^4.3.0

  animated_splash_screen: ^1.3.0
  flutter_spinkit: ^5.1.0

  flutter_svg: ^1.1.4

  google_fonts: ^3.0.1

  introduction_screen: ^3.0.2

  pin_code_fields: ^7.4.0

  #google_map + location
  google_maps_flutter: ^2.2.0
  flutter_polyline_points: ^1.0.0
  geolocator: ^9.0.1
  geocoding: ^2.0.5
  location: ^4.2.0

  #payment
  pay: ^1.0.11


dev_dependencies:
  build_runner:
  flutter_gen_runner:

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/OpenSans-Italic-VariableFont_wdth,wght.ttf
          style: italic
